5/6/2019, pre-submission todo: 
- fix "FIXME" tags in testthat.

07/02/2018

- to pass check() and BiocCheck::check(). 
  -- no "inst/doc/VariantExperiment.html" detected. 

- adding new stats functions: 
  -- BCF2VE, VCF2VE (vcf.fn argument?)  -- only keep VCF2VE now!
- add examples for: 
  - VCF2VE  -- done!
  - makeSEFromGDS -- done!
  - showAvailable() -- done!
  - ... 
  
- vignette.  -- done! 
- documentation for arguments.  -- done! 
- gdsfile() return an atomic vector. (currently using vapply).  -- done!
- construct a valid empty VE object, by `VariantExperiment()`.  -- done! 
- disable the "gdsfile()<-" setter function. -- done!
- consistent argument values. -- done!
- "makeSummarizedExperimentFromVCF(info.import)" with "makeSummarizedExperimentFromGDS(info.columns)". Make default as "NULL" to import all info, and when "character(0)", import nothing. 

- renaming: 
  save/loadGDSSummarizedExperiment ==> save/loadVariantExperiment  -- done! 
  keep "makeSummarizedExperimentFromGDS"  -- done!
  VCF2VE ==> makeSummarizedExperimentFromVCF ??  -- done!  

- bugs
  - ?VariantExperiment-methods (last line). -- done!
  - vignette not generating in inst/doc.    -- done! 
	-- DESCRIPTION: VignetteBuilder: knitr  Suggests: knitr

- add example ve.gds, ve.rd file under "inst/extdata".   ?? 
- reactivate the "gdsfile<-" setter function... ?? 


- bugs:   -- workaround fixed!
  -- devtools::document(), first time document() reserves SeqVarTools::titv() methods/functions, second time document() lost all methods for "SeqVarGDSClass"...
  ## unable to find an inherited method for function ‘meanBySample’ for signature ‘"SeqVarGDSClass"’
  ## FIX workaround fix: library(SeqVarGDSClass) when developing. Only problem with "devtools", will not affect the check().  


-- question for martin: 
1. VariantExperiment() constructor, should we copy all argument documentations from SummarizedExperiment? 

2. next phase:
- add more sample related stats functions. (need real data)
- add block processing, and apply functions. 
- connection with VariantAnnotation (collapsedVCF? in memory)?
- for annotation: AnnotationHub? (ensemblVEP, VariantFiltering..., dbsnp pkgs). 
- filtering, using rowRanges, overlap...
- sample.annotation related stat analysis: mendelian errors? (use family info, test!!) - next phase!
- association test associated analysis?  -- next phase!
- gds attributes to save in metadata? 
  -- header info. no need to save vcf file now... wait until connecting to VariantAnnotation. 
  -- sample.order / snp.order, VCF version, ... not super important for VE analysis. 



## Vignette
1. introduction. 
2. installation. 
3. BackGround
- GDSArray
- DelayedDataFrame
4. VariantExperiment-package
- VariantExperiment-class (class, setters and getters)
- VariantExperiment-methods (VCF2VE, titv... vcf related.)
- common manipulations... (subsetting, save new VE file, load VE file, ... )
FIXME: slot setter? gdsfile() <-
FIXME: saveGDSSE(dir="my_gds_se") or use tempfile() here?   -- use "tempdir()" in vignette. 

5. sessionInfo
